name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0 # Рекомендуется использовать последнюю версию
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
            # 1. Создаем папку, если её нет
            mkdir -p ${{ secrets.PROJECT_DIR }} && \
            
            # 2. Переходим в неё
            cd ${{ secrets.PROJECT_DIR }} && \
            
            # 5. Обновляем код и запускаем Docker
            git pull origin main && \
            
            # 6. Остановка старых контейнеров и удаление потерянных связей
            sudo docker-compose down --remove-orphans && \
            
            sudo docker-compose up --build -d
          " 
